create table comments (
    id integer primary key generated by default as identity,
    content text not null,
    modified timestamptz default now() not null,
    author text not null
);

alter table comments
    add column
        post_id integer references posts(id) on delete cascade not null;